on:
  push:
  workflow_dispatch:
  
name: ğŸš€ Deploy website on webetu
jobs:
  web-deploy:
    name: ğŸ‰ Deploy
    runs-on: ubuntu-latest
    steps:
    - name: ğŸšš Get latest code
      uses: actions/checkout@v2
    
    - name: ğŸ” Preparing files (remove git directories)
      run: |
        rm -rf .git/ .github/
      
    - name: ğŸ“‚ List current files
      run: ls -la
    
    - name: ğŸ“‚ Sync files
      uses: wlixcc/SFTP-Deploy-Action@v1.2.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USER }}
        password: ${{ secrets.FTP_PASS }}
        local_path: '.'
        remote_path: ${{ secrets.FTP_PATH }}
